/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

/**
 *
 * @author eduar
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tituloMiHorario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelRound1 = new com.login.PanelRound();
        nuevoHorario_jlabel = new javax.swing.JLabel();
        mas_horario_jlabel = new javax.swing.JLabel();
        lunesJlabel = new javax.swing.JLabel();
        diaDeLaSemanaCorte = new javax.swing.JLabel();
        miercolesjLabel = new javax.swing.JLabel();
        martesjLabel7 = new javax.swing.JLabel();
        juevesjLabel = new javax.swing.JLabel();
        viernesjLabel = new javax.swing.JLabel();
        clase_14pm = new javax.swing.JLabel();
        dia_2 = new javax.swing.JLabel();
        dia_3 = new javax.swing.JLabel();
        dia_4 = new javax.swing.JLabel();
        dia_5 = new javax.swing.JLabel();
        dia_6 = new javax.swing.JLabel();
        clase_6am = new javax.swing.JLabel();
        clase_7am = new javax.swing.JLabel();
        clase_8am = new javax.swing.JLabel();
        clase_9am = new javax.swing.JLabel();
        clase_10am = new javax.swing.JLabel();
        clase_11am = new javax.swing.JLabel();
        clase_12am = new javax.swing.JLabel();
        clase_13pm = new javax.swing.JLabel();
        clase_18pm = new javax.swing.JLabel();
        clase_15pm = new javax.swing.JLabel();
        clase_16pm = new javax.swing.JLabel();
        clase_17pm = new javax.swing.JLabel();
        clase_21pm = new javax.swing.JLabel();
        clase_20pm = new javax.swing.JLabel();
        clase_19pm = new javax.swing.JLabel();
        Separator9am = new javax.swing.JSeparator();
        Separator6am = new javax.swing.JSeparator();
        Separator7am = new javax.swing.JSeparator();
        Separator8am = new javax.swing.JSeparator();
        Separator10am = new javax.swing.JSeparator();
        Separator11am = new javax.swing.JSeparator();
        Separator12am = new javax.swing.JSeparator();
        Separator13pm = new javax.swing.JSeparator();
        Separator14pm = new javax.swing.JSeparator();
        Separator15pm = new javax.swing.JSeparator();
        Separator16pm = new javax.swing.JSeparator();
        Separator17pm = new javax.swing.JSeparator();
        Separator18pm = new javax.swing.JSeparator();
        Separator19pm = new javax.swing.JSeparator();
        Separator20pm = new javax.swing.JSeparator();
        Separator21pm = new javax.swing.JSeparator();
        panelRound2 = new com.login.PanelRound();
        panelRound3 = new com.login.PanelRound();
        jPanel2 = new javax.swing.JPanel();
        nombreEstudianteJlabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloMiHorario.setFont(new java.awt.Font("Inter Black", 0, 18)); // NOI18N
        tituloMiHorario.setText("Mi horario");
        jPanel1.add(tituloMiHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 111, 36));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel1.setText("Mes, dia_comienso-dia_final");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 210, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 110, 50));

        panelRound1.setBackground(new java.awt.Color(255, 51, 51));
        panelRound1.setRoundBottomLeft(10);
        panelRound1.setRoundBottomRight(10);
        panelRound1.setRoundTopLeft(10);
        panelRound1.setRoundTopRight(10);
        panelRound1.setLayout(new java.awt.GridBagLayout());

        nuevoHorario_jlabel.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        nuevoHorario_jlabel.setText("+ ");
        panelRound1.add(nuevoHorario_jlabel, new java.awt.GridBagConstraints());

        mas_horario_jlabel.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        mas_horario_jlabel.setText("Nuevo horario");
        panelRound1.add(mas_horario_jlabel, new java.awt.GridBagConstraints());

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 120, 50));

        lunesJlabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lunesJlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lunesJlabel.setText("Lunes");
        jPanel1.add(lunesJlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 100, 20));

        diaDeLaSemanaCorte.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        diaDeLaSemanaCorte.setText("Semana corte");
        jPanel1.add(diaDeLaSemanaCorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, 30));

        miercolesjLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        miercolesjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        miercolesjLabel.setText("Miercoles");
        jPanel1.add(miercolesjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 100, 20));

        martesjLabel7.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        martesjLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        martesjLabel7.setText("Martes");
        jPanel1.add(martesjLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 100, 20));

        juevesjLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        juevesjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        juevesjLabel.setText("Jueves");
        jPanel1.add(juevesjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 100, 20));

        viernesjLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        viernesjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viernesjLabel.setText("Viernes");
        jPanel1.add(viernesjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 100, 20));

        clase_14pm.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        clase_14pm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clase_14pm.setText("14:00");
        jPanel1.add(clase_14pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 100, 20));

        dia_2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        dia_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dia_2.setText("2");
        jPanel1.add(dia_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 100, 20));

        dia_3.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        dia_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dia_3.setText("3");
        jPanel1.add(dia_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 100, 20));

        dia_4.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        dia_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dia_4.setText("4");
        jPanel1.add(dia_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 100, 20));

        dia_5.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        dia_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dia_5.setText("5");
        jPanel1.add(dia_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 100, 20));

        dia_6.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        dia_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dia_6.setText("1");
        jPanel1.add(dia_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 100, 20));

        clase_6am.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        clase_6am.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clase_6am.setText("6:00");
        jPanel1.add(clase_6am, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 100, 20));

        clase_7am.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        clase_7am.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clase_7am.setText("7:00");
        jPanel1.add(clase_7am, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, 20));

        clase_8am.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        clase_8am.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clase_8am.setText("8:00");
        jPanel1.add(clase_8am, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 20));

        clase_9am.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        clase_9am.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clase_9am.setText("9:00");
        jPanel1.add(clase_9am, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 20));

        clase_10am.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        clase_10am.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clase_10am.setText("10:00");
        jPanel1.add(clase_10am, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 100, 20));

        clase_11am.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        clase_11am.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clase_11am.setText("11:00");
        jPanel1.add(clase_11am, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 100, 20));

        clase_12am.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        clase_12am.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clase_12am.setText("12:00");
        jPanel1.add(clase_12am, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 100, 20));

        clase_13pm.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        clase_13pm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clase_13pm.setText("13:00");
        jPanel1.add(clase_13pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 100, 20));

        clase_18pm.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        clase_18pm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clase_18pm.setText("18:00");
        jPanel1.add(clase_18pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 100, 20));

        clase_15pm.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        clase_15pm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clase_15pm.setText("15:00");
        jPanel1.add(clase_15pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 100, 20));

        clase_16pm.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        clase_16pm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clase_16pm.setText("16:00");
        jPanel1.add(clase_16pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 100, 20));

        clase_17pm.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        clase_17pm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clase_17pm.setText("17:00");
        jPanel1.add(clase_17pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 100, 20));

        clase_21pm.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        clase_21pm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clase_21pm.setText("21:00");
        jPanel1.add(clase_21pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 100, 20));

        clase_20pm.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        clase_20pm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clase_20pm.setText("20:00");
        jPanel1.add(clase_20pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 100, 20));

        clase_19pm.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        clase_19pm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clase_19pm.setText("19:00");
        jPanel1.add(clase_19pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 100, 20));
        jPanel1.add(Separator9am, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 600, 10));
        jPanel1.add(Separator6am, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 600, 10));
        jPanel1.add(Separator7am, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 600, 10));
        jPanel1.add(Separator8am, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 600, 10));
        jPanel1.add(Separator10am, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 600, 10));
        jPanel1.add(Separator11am, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 600, 10));
        jPanel1.add(Separator12am, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 600, 10));
        jPanel1.add(Separator13pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 600, 10));
        jPanel1.add(Separator14pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 600, 10));
        jPanel1.add(Separator15pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 600, 10));
        jPanel1.add(Separator16pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 600, 10));
        jPanel1.add(Separator17pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 600, 10));
        jPanel1.add(Separator18pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 600, 10));
        jPanel1.add(Separator19pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 600, 10));
        jPanel1.add(Separator20pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 620, 600, 10));
        jPanel1.add(Separator21pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 650, 600, 10));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound3.setBackground(new java.awt.Color(255, 51, 51));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundTopLeft(20);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panelRound2.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 40));

        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 110, 40));

        nombreEstudianteJlabel.setFont(new java.awt.Font("Inter ExtraBold", 0, 18)); // NOI18N
        nombreEstudianteJlabel.setText("Nombre del estudiante");

        jLabel2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel2.setText("Semestre");

        jLabel3.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel3.setText("Carrera");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nombreEstudianteJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(nombreEstudianteJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separator10am;
    private javax.swing.JSeparator Separator11am;
    private javax.swing.JSeparator Separator12am;
    private javax.swing.JSeparator Separator13pm;
    private javax.swing.JSeparator Separator14pm;
    private javax.swing.JSeparator Separator15pm;
    private javax.swing.JSeparator Separator16pm;
    private javax.swing.JSeparator Separator17pm;
    private javax.swing.JSeparator Separator18pm;
    private javax.swing.JSeparator Separator19pm;
    private javax.swing.JSeparator Separator20pm;
    private javax.swing.JSeparator Separator21pm;
    private javax.swing.JSeparator Separator6am;
    private javax.swing.JSeparator Separator7am;
    private javax.swing.JSeparator Separator8am;
    private javax.swing.JSeparator Separator9am;
    private javax.swing.JPanel background;
    private javax.swing.JLabel clase_10am;
    private javax.swing.JLabel clase_11am;
    private javax.swing.JLabel clase_12am;
    private javax.swing.JLabel clase_13pm;
    private javax.swing.JLabel clase_14pm;
    private javax.swing.JLabel clase_15pm;
    private javax.swing.JLabel clase_16pm;
    private javax.swing.JLabel clase_17pm;
    private javax.swing.JLabel clase_18pm;
    private javax.swing.JLabel clase_19pm;
    private javax.swing.JLabel clase_20pm;
    private javax.swing.JLabel clase_21pm;
    private javax.swing.JLabel clase_6am;
    private javax.swing.JLabel clase_7am;
    private javax.swing.JLabel clase_8am;
    private javax.swing.JLabel clase_9am;
    private javax.swing.JLabel diaDeLaSemanaCorte;
    private javax.swing.JLabel dia_2;
    private javax.swing.JLabel dia_3;
    private javax.swing.JLabel dia_4;
    private javax.swing.JLabel dia_5;
    private javax.swing.JLabel dia_6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel juevesjLabel;
    private javax.swing.JLabel lunesJlabel;
    private javax.swing.JLabel martesjLabel7;
    private javax.swing.JLabel mas_horario_jlabel;
    private javax.swing.JLabel miercolesjLabel;
    private javax.swing.JLabel nombreEstudianteJlabel;
    private javax.swing.JLabel nuevoHorario_jlabel;
    private com.login.PanelRound panelRound1;
    private com.login.PanelRound panelRound2;
    private com.login.PanelRound panelRound3;
    private javax.swing.JLabel tituloMiHorario;
    private javax.swing.JLabel viernesjLabel;
    // End of variables declaration//GEN-END:variables
}
