/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import java.awt.Color;


public class Login extends javax.swing.JFrame {

    int xMouse, yMouse;
    
            
            
            
            
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelRound1 = new com.login.PanelRound();
        panelRound7 = new com.login.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelRound3 = new com.login.PanelRound();
        panelRound4 = new com.login.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelRound5 = new com.login.PanelRound();
        header = new javax.swing.JPanel();
        exitButton = new javax.swing.JPanel();
        exitButtonlabel = new javax.swing.JLabel();
        panel_izquierdo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        titulo_usuario = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        titulo_contraseña = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        panel_login = new com.login.PanelRound();
        login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setPreferredSize(new java.awt.Dimension(800, 450));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(238, 62, 62));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound7.setRoundBottomRight(10);
        panelRound7.setRoundTopRight(10);

        jLabel10.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel10.setText("Fisica I");

        jLabel11.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel11.setText("Julio Madera");

        jLabel12.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel12.setText("7am - 10pm");

        javax.swing.GroupLayout panelRound7Layout = new javax.swing.GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound1.add(panelRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 150, 90));

        panelRound3.setBackground(new java.awt.Color(0, 0, 4));
        panelRound3.setRoundBottomLeft(10);
        panelRound3.setRoundTopLeft(10);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        panelRound1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 20, 90));

        panelRound4.setRoundBottomRight(10);
        panelRound4.setRoundTopRight(10);

        jLabel3.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel3.setText("Calculo Integral");

        jLabel6.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel6.setText("Kelly Oviedo");

        jLabel7.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel7.setText("2pm - 4pm");

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound1.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        panelRound5.setBackground(new java.awt.Color(0, 0, 4));
        panelRound5.setRoundBottomLeft(10);
        panelRound5.setRoundTopLeft(10);

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        panelRound1.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        background.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 280, 450));

        header.setBackground(new java.awt.Color(217, 217, 217));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(217, 217, 217));

        exitButtonlabel.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        exitButtonlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitButtonlabel.setText("X");
        exitButtonlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButtonlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonlabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonlabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonlabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitButtonLayout = new javax.swing.GroupLayout(exitButton);
        exitButton.setLayout(exitButtonLayout);
        exitButtonLayout.setHorizontalGroup(
            exitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButtonlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        exitButtonLayout.setVerticalGroup(
            exitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButtonlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 763, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        panel_izquierdo.setBackground(new java.awt.Color(217, 217, 217));
        panel_izquierdo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Inter ExtraBold", 1, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Bienvenido de nuevo!");
        titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titulo.setMaximumSize(new java.awt.Dimension(115, 15));
        panel_izquierdo.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 87, 286, 26));

        titulo_usuario.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        titulo_usuario.setText("Usuario:");
        panel_izquierdo.add(titulo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 139, -1, -1));

        usuario.setBackground(new java.awt.Color(217, 217, 217));
        usuario.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        usuario.setForeground(new java.awt.Color(51, 0, 0));
        usuario.setText("Usuario de elysa");
        usuario.setBorder(null);
        usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuarioMousePressed(evt);
            }
        });
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        panel_izquierdo.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 169, 303, 29));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        panel_izquierdo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 204, 303, 9));

        titulo_contraseña.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        titulo_contraseña.setText("Contraseña:");
        panel_izquierdo.add(titulo_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 225, 87, -1));

        contraseña.setBackground(new java.awt.Color(217, 217, 217));
        contraseña.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        contraseña.setText("********");
        contraseña.setBorder(null);
        contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contraseñaMousePressed(evt);
            }
        });
        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });
        panel_izquierdo.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 249, 303, 32));
        panel_izquierdo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 287, 303, 10));

        panel_login.setBackground(new java.awt.Color(231, 231, 231));
        panel_login.setRoundBottomLeft(20);
        panel_login.setRoundBottomRight(20);
        panel_login.setRoundTopLeft(20);
        panel_login.setRoundTopRight(20);
        panel_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_loginMouseExited(evt);
            }
        });
        panel_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(204, 204, 204));
        login.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("Entrar");
        login.setToolTipText("");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        panel_login.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        panel_izquierdo.add(panel_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 303, 303, 40));

        background.add(panel_izquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 450));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
       
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitButtonlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonlabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitButtonlabelMouseClicked

    private void panel_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_loginMouseEntered
        panel_login.setBackground(Color.white);
    }//GEN-LAST:event_panel_loginMouseEntered

    private void panel_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_loginMouseExited
        panel_login.setBackground(new Color(231,231,231, 255));
    }//GEN-LAST:event_panel_loginMouseExited

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        panel_login.setBackground(Color.white);
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        panel_login.setBackground(new Color(231,231,231, 255));
    }//GEN-LAST:event_loginMouseExited

    private void exitButtonlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonlabelMouseEntered
        exitButtonlabel.setForeground(Color.red);
    }//GEN-LAST:event_exitButtonlabelMouseEntered

    private void exitButtonlabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonlabelMouseExited
        exitButtonlabel.setForeground(Color.black);
    }//GEN-LAST:event_exitButtonlabelMouseExited

    private void usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioMousePressed
        if(usuario.getText().equals("Usuario de elysa")){
            usuario.setText("");
        }
        
        if(String.valueOf(contraseña.getPassword()).isEmpty()){
            contraseña.setText("********");
        }
        
    }//GEN-LAST:event_usuarioMousePressed

    private void contraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñaMousePressed
        if(String.valueOf(contraseña.getPassword()).equals("********")){
        contraseña.setText("");
        }
        
        if(usuario.getText().isEmpty()){
        usuario.setText("Usuario de elysa");
        }
    }//GEN-LAST:event_contraseñaMousePressed

    private void panel_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_loginMouseClicked
        System.out.println("Usuario: " + usuario.getText() + " Contrasena: " + String.valueOf(contraseña.getPassword()));
    }//GEN-LAST:event_panel_loginMouseClicked

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        System.out.println("Usuario: " + usuario.getText() + " Contrasena: " + String.valueOf(contraseña.getPassword()));
    }//GEN-LAST:event_loginMouseClicked
                  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JPanel exitButton;
    private javax.swing.JLabel exitButtonlabel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel login;
    private com.login.PanelRound panelRound1;
    private com.login.PanelRound panelRound2;
    private com.login.PanelRound panelRound3;
    private com.login.PanelRound panelRound4;
    private com.login.PanelRound panelRound5;
    private com.login.PanelRound panelRound6;
    private com.login.PanelRound panelRound7;
    private javax.swing.JPanel panel_izquierdo;
    private com.login.PanelRound panel_login;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo_contraseña;
    private javax.swing.JLabel titulo_usuario;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
